title: EscolhaUmaLicenca.com.br
relative_permalinks: false
markdown: kramdown

rules:

  required:
    include-copyright:
      description: Inclua uma cópia da licença e aviso de direitos autorais com o código.
      label: Aviso de licença e direitos autorais
    document-changes:
      description: Indica alterações significativas feitas no código.
      label: Mudanças de Estado
    disclose-source:
      description: O código-fonte deve ser disponibilizado ao distribuir o software. Em caso de LGPL, o fonte da biblioteca (e não do programa inteiro) deve ser disponibilizado.
      label: Divulgação de código-fonte
    library-usage:
      description: A biblioteca pode ser usada dentro de um aplicativo não-open-source.
      label: Uso de biblioteca
    rename:
      description: Você deve alterar o nome do software se você o alterar.
      label: Renomear

  permitted:
    commercial-use:
      description: O software e seus derivados podem ser usados para fins comerciais.
      label: Uso comercial
    modifications:
      description: O software pode ser modificado.
      label: Modificação
    distribution:
      description: Você pode distribuir o software.
      label: Distribuição
    sublicense:
      description: Você pode conceder uma sublicença para modificar e distribuir o software a terceiros não incluídos na licença.
      label: Sublicenciamento
    private-use:
      description: Você pode usar e modificar o software sem distribuí-lo.
      label: Uso Privado
    patent-grant:
      description: Essa licença fornece uma concessão expressa de direitos de patente do contribuinte para o destinatário.
      label: Concessão de Patente

  forbidden:
    trademark-use:
      description: Embora isso possa parecer implicitamente verdadeiro em todas as licenças, esta licença afirma explicitamente que você não pode usar os nomes, logos ou marcas de contribuidores.
      label: Uso de Marca Registrada
    no-liability:
      description: O software é fornecido sem garantia e o autor/licença do software não pode ser responsabilizado por perdas e danos.
      label: Responsabilidade Assegurada
    no-sublicense:
      description: Você não pode conceder uma sublicença para modificar e distribuir o software a terceiros não incluídos na licença.
      label: Sublicenciamento
    modifications:
      description: O software não pode ser modificado.
      label: Modificação
    distribution:
      description: O software não pode ser distribuído.
      label: Distribuição
    sublicense:
      description: Você não pode conceder uma sublicença para modificar e distribuir o software a terceiros não incluídos na licença.
      label: Sublicenciamento

exclude:
  - CNAME
  - Gemfile*
  - script
  - vendor
